### ISSUE TITLE
snackbar v-model only working in non strict mode

### ISSUE THREAD

**Issue by dwfee** [jeffreybiles/vue-screencasts-nuxt#2]
Hi, Jeff,
greetings from Germany! I like your tutorials a lot. Helped me adress some problems with my stuff. When implementig the snackbar as you did , I get get error: do not mutate vuex store state outside mutation handlers, which is , because state of showing switches when changing to false. 
Works without problems, when I turn of strict mode.

**Comment by bolokoz** [comment]
Having this problem too. Can't figure out an elegant workaround

**Comment by jeffreybiles** [comment]
Sorry about the long delay on this!

I'll be looking into it soon (within the next week), then making a video about the solution.

**Comment by jeffreybiles** [comment]
Alright, here's the video: https://www.vuescreencasts.com/watch/185

And here's the commit with relevant code: https://github.com/jeffreybiles/vue-screencasts-nuxt/commit/15898689aa75185a7058c8590ad16b6c0fb61137

Thanks for reporting the issue!
