### ISSUE TITLE
Issue: Hostname Changed

### ISSUE THREAD

**Issue by ruthylevi** [jeffreybiles/vue-screencasts-nuxt#3]
Hello! I came across the YouTube video titled "Building Complex Data Tables with Vuetify's v-data-table and VueJS" and found this Github repo from here. I installed it, and now I'm having issues with my terminal. I am now seeing myname@host-vlep1-63 instead of myname@(what it used to be). How do I correct this, and uninstall any other changes that were made? Thanks!

**Comment by jeffreybiles** [comment]
Hey, thanks for watching!

As far as I know, there shouldn't be anything in this repo that would mess with your terminal.  It's all Nuxt code.

Is there anything else you've done recently that could have caused the change?  If not, a good next step might be asking about it in the Nuxt Discord chat.
